blank_issues_enabled: false
contact_links:
  - name: Discord community
    url: https://discord.gg/WmMYYQp
    about: You can reach out to Storyblok Discord community.

  - name: Storyblok Help Center/Service Desk
    url: https://storyblok.atlassian.net/servicedesk/customer/portals
    about: You can raise a request for Storyblok Service Desk.

  - name: Feature Requests
    url: https://feedback.storyblok.com/b/feature-requests/
    about: You can post your Feature Requests and vote for others as well.
